### ISSUE TITLE
Add maxRetries parameters to controller

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1031]
/kind feature

**What happened**:

```
const (
	// maxRetries is the number of times a volcano job will be retried before it is dropped out of the queue.
	// With the current rate-limiter in use (5ms*2^(maxRetries-1)) the following numbers represent the times
	// a volcano job is going to be requeued:
	//
	// 5ms, 10ms, 20ms, 40ms, 80ms, 160ms, 320ms, 640ms, 1.3s, 2.6s, 5.1s, 10.2s, 20.4s, 41s, 82s
	maxRetries = 15
)
```

the maxRetries is hard coded.

And In my scenario, I hope the job controller keep retrying, just like other k8s controllers.

So, is it ok to add  a maxRetries parameter, default value is 15, when set to -1, it means retry endlessly

**Environment**:
- Volcano Version: v1.0.1

**Comment by hzxuzhonghu** [comment]
I am ok with this requirement and welcome a pr addressing this.

**Comment by liuchintao** [comment]
@hzxuzhonghu hello, can I ask a question? I was puzzled that why Volcano Job Controller only tried to execute action 15 times.
Are there any restrictions on Job Controller or job cache?

**Comment by hzxuzhonghu** [comment]
Actually we think 15 is enough, the retry can happen when error occur, maybe `ratelimit`, `transient network issue`. With limited retry, it can recover automatically.


>Are there any restrictions on Job Controller or job cache?

I am not sure i understand your question

**Comment by liuchintao** [comment]
Thanks for your reply~

As you said, 15 is sufficient in most cases, like ratelimit, transient network issue. 

However, what is the expected behavior, when it still failed after 15 retries? I think it is possible.

For example, in my namespace `foo`, there is a `resource quota` for 5 cpus.

```yaml
  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: quota-cpu
    namespace: foo
  spec:
    hard:
      cpu: "5"
```

And my mpijob just need 5 cpu, a mpi-launcher need 1 cpu, 2 mpi-workers need 2 cpu separately. Everything looks good.

But before I start my mpi job, I start a pod that consumes 2 cpu. 
Now I just have 2 mpi pods, a launcher and a worker, I have to wait for pod complete and release resources.
But now job controller reach 15 retries, and drop this `req` from worker's queue, 
and I never get the last pod any more, even the former pod releases resources.

I wonder if the job controller can retry forever or release pods' resources but keep error msg? Maybe I could provide a pr.

**Comment by hzxuzhonghu** [comment]
Fair point. Welcome to file a pr.  IMO, We could make use of the existing `MaxRetry` in Job.Spec.

**Comment by liuchintao** [comment]
lol~~~ that's fine

**Comment by shinytang6** [comment]
hey there, how is the progress? I think it is more reasonable to leave the `maxRetries` parameter to the user, can l take this as a try?

**Comment by hzxuzhonghu** [comment]
Sure.

**Comment by Thor-wl** [comment]
> hey there, how is the progress? I think it is more reasonable to leave the `maxRetries` parameter to the user, can l take this as a try?

Welcome to your contribution!
