### ISSUE TITLE
Metrics not available `kube_pod_volcano_container_resource_requests`

### ISSUE THREAD

**Issue by tahsinrahman** [volcano-sh/volcano#1587]
**What happened**:
The grafana dashboards expects metrics like `kube_pod_volcano_container_resource_requests` `kube_pod_volcano_container_status_running` etc, these metrics are not available.

**What you expected to happen**:
The installer yaml manifests should have prometheus rules to generate these metrics

**How to reproduce it (as minimally and precisely as possible)**:
Install volcano helm chart, then see grafana dashboard

**Comment by Tammy-kunyu** [comment]
> /cc @Tammy-kunyu Can you help about that?

Okay，I will have a look.

**Comment by Thor-wl** [comment]
> > /cc @Tammy-kunyu Can you help about that?
> 
> Okay，I will have a look.

If there's any process, please note here. THX.

**Comment by lx1036** [comment]
@tahsinrahman  volcano fork kube-state-metrics, and add some custom metrics, like `kube_pod_volcano_container_resource_requests`, you can see commit https://github.com/volcano-sh/kube-state-metrics/commit/a91719d5dc2c4bb814802456ad31ddff0c1d2b7e .
so, you should only deploy this forked kube-state-metrics. and config it job name in your prometheus.yml, of course, the volcano repo has add it https://github.com/volcano-sh/volcano/blob/master/installer/volcano-monitoring-latest.yaml#L100-L102 .

**Comment by tahsinrahman** [comment]
@lx1036 in that case, the image should refer to the forked kube-state-metrics here https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/templates/kubestatemetrics.yaml#L158

**Comment by tahsinrahman** [comment]
one more thing, instead of forking kube-state-metrics and adding these metrics from there, we can actually write prometheus recording rules, so it'd generate the custom metrics from given promql expression. In that case, if someone already has a prometheus/grafana setup in their cluster, they can just import the recording rule, they won't have to deploy the prom/grafana and forked kube-state-metrics from here.

**Comment by avinovarov** [comment]
Agree that solution suggested by @tahsinrahman with custom recording rules looks better than installing forked (severely outdated) instance of kube-state-metrics.

Meanwhile, observing the same issue here - Volcano 1.4.0 installed via helm chart, installs `kube-state-metrics` pod running on image version 1.9.7, and does not export any of `kube_pod_volcano_*` metrics. And as we already have Prometheus stack installed into a different namespace, there are now two `kube-state-metrics` pods in the cluster which doesn't make sense.

So the questions persist:
- which image to specify in `kubestatemetrics.yaml` to use Volcano's forked `kube-state-metrics`?
- perhaps it's good idea to parametrise things in helm chart's `values.yaml`, something like

```kube-state-metrics
  enabled: true 
  image: "volcano.sh/kube-state-metrics:v2.1.1" # could not find any publicly available as of now
  namespace: "monitoring"
  resources: # it is 'best-effort' now, not the best option
    requests...
    limits...
```

It occures that some well-detailed help/readme could be useful, because currently we have `prometheus-server-conf` configmap deployed to `volcano-system` namespace, whose usefulness is questionable as we already have our instance of Prometheus running in different namespace.

Thanks.

**Comment by avinovarov** [comment]
Would also like mention that things like this https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/templates/grafana.yaml#L136 are pretty questionable in general for http traffic, and largely counter-intuitive without a detailed description.

**Comment by Thor-wl** [comment]
I agree with the solution mentioned above. Would you like to give a PR for that?

**Comment by hwdef** [comment]
This problem still exists in the latest version

**Comment by avinovarov** [comment]
The issue is still here with us, would suggest keeping it open.

Sorry, not sure if I'm able to find the time for PR for now, but I'd start with removing entire `volcano-monitoring` namespace from helm chart to begin with.

**Comment by jeffreyyjp** [comment]
@azxs6400949 They use the forked kube-state-metrics to handle custom metrics, and don't provide the public image, the repo(https://github.com/volcano-sh/volcano/blob/master/installer/volcano-monitoring-latest.yaml) still use offical image, which is not the forked version.

**Comment by robscc** [comment]
I have the same problem , would suggest keeping it open.

**Comment by netscrol2016** [comment]
+
