### ISSUE TITLE
Whether to verify data before invoking the unmarshal function

### ISSUE THREAD

**Issue by ounijang** [volcano-sh/volcano#1600]
**Suggest ：**
Check whether the input data needs to be verified or checked before the unmarshal function is invoked to ensure that no security problem occurs. For example, excessive memory may be applied for during deserialization, causing memory exhaustion.

**Environment:**

Volcano Version:v1.2.0
Kubernetes version (use kubectl version):1.17.3
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):unbuntu 18.04
Kernel (e.g. uname -a):
Install tools:
Others: 
I found that the code invoked was in the **generated.pb.go** file.

**Comment by Thor-wl** [comment]
I agree with that security problem is very import for system. But I think it's hard for Volcano to deal with doing the business above. The problems are as follows:
1. How to define it's a security problem? Such as the example mentions above, excessive memory may be a risk. But what's the rule to judge the risk? It's hard to say because it has a lot to do with your application or business. As a general scheduling engine, Volcano knows little about that.
2. Maybe we need a detail list about risk items. It can act as the base of development.
