### ISSUE TITLE
preemption function is based on job priority in

### ISSUE THREAD

**Issue by huone1** [volcano-sh/volcano#1642]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
would you help to share more info?

**Comment by wpeng102** [comment]
@k82cn by default, user will config gang plugin for the first tiers. If user also config preempt for the action and want to use queue fair-share function. The `gang` plugin will reject reclaim because preemptor priority is equal with preemptees's

https://github.com/volcano-sh/volcano/blob/44ec8eb28df26fbacd03ab15edabfc5916900c25/pkg/scheduler/plugins/gang/gang.go#L90-L94

related issue https://github.com/volcano-sh/volcano/issues/1619
