### ISSUE TITLE
ssh failed sometimes

### ISSUE THREAD

**Issue by zhenxiu** [volcano-sh/volcano#1972]
when i use mpi job, 
ssh: Could not resolve hostname ***-job: Name or service not known.

this usually happened, especially more workers

**Comment by william-wang** [comment]
@zhenxiu thanks for your reporting. Would you like to provide the basic information like mpi job yaml, Volcano version and reproduce steps?

**Comment by zhenxiu** [comment]
i use v1.2.0 and official mpi yaml; differently, i use my own image with mpi installed

**Comment by yongqiangz** [comment]
maybe you can check if all the workers are running when the master begin to run， Sometimes the worker may be pulling docker images

**Comment by zhenxiu** [comment]
> maybe you can check if all the workers are running when the master begin to run， Sometimes the worker may be pulling docker images

all workers are running

**Comment by snirkop89** [comment]
@zhenxiu did you find any solution for that?
it happens in version 1.5.1 also with mpi-example file. With the IP ssh works fine.

**Comment by snirkop89** [comment]
Yes. I'm using the example you sent. I verified the hosts name in the file are correct by echoing them before the command.
I read in one of the issues that it might be related to the user running the image - should be root, and DNS problem.

However, I'm using an image we use to run successfully MPIJob with multi node, but since the mpi-operator project doesn't support sending volcano options (for example, minAvailable), I'm trying to move to volcano job.

Not sure it's related, but the vcjob creates a service and set its port to 1. mpijob creates a headless services without any ports specified. I tried to edit the svc when the job is already live, but it didn't affect the result.
