### ISSUE TITLE
cannot set task.maxRetry==0

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#2012]
when set maxRetry == 0, it was reset to 3。 what i want is not retry， turn to taskFailed immediately

https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/cache/cache.go#L317

**Comment by k82cn** [comment]
if `maxRetry < 0`, set it to 3 :)

**Comment by merryzhou** [comment]
> if `maxRetry < 0`, set it to 3 :)

how to compatible with existing job?

**Comment by zhiyxu** [comment]
> when set maxRetry == 0, it was reset to 3。 what i want is not retry， turn to taskFailed immediately
> 
> https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/cache/cache.go#L317

@merryzhou We also had the same problem.
In fact, the `maxRetry` field of volcanoJob is different from the `backoffLimit` field of the   native Kubernetes Job:
`backoffLimit` refers to the number of retries after the initial run of Failed, so `the maximum number of runs = 1 + backoffLimit`;
The `maxRetry` refers to the maximum number of runs. For example, if `maxRetry`=3, after the initial run fails, it will **only retry twice**.
So in my perspective, **if you don't want volcanoJob to retry, you should configure maxRetry to 1 instead of 0. **

**Comment by liuchintao** [comment]
> > when set maxRetry == 0, it was reset to 3。 what i want is not retry， turn to taskFailed immediately
> > https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/cache/cache.go#L317
> 
> @merryzhou We also had the same problem. In fact, the `maxRetry` field of volcanoJob is different from the `backoffLimit` field of the native Kubernetes Job: `backoffLimit` refers to the number of retries after the initial run of Failed, so `the maximum number of runs = 1 + backoffLimit`; The `maxRetry` refers to the maximum number of runs. For example, if `maxRetry`=3, after the initial run fails, it will **only retry twice**. So in my perspective, **if you don't want volcanoJob to retry, you should configure maxRetry to 1 instead of 0.**

So, what's the meaning of `maxRetry`?  `maxRetry` should represent the maximum number of retried.
Perhaps, `maxTry` or `maxRun` is more appropriate to indicate the maximum number of times of runs.
