### ISSUE TITLE
Suggest to add a field to queue.spec indicating queue open or closed

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#2058]
#### What would you like to be added:

Add a field to queue.spec, by modifying this field, the queue can be turned on or off.

#### Why is this needed:

After adding this field, the user can open or close the queue through kubectl.

REF: #1687

#### optional name:

* switch: open/close
* state: open/close
* open: true/false
* ...

**Comment by k82cn** [comment]
Can we delete all jobs fristly, and then delete the queue; we can handle those actions in `QueueController`, similar to namespace.

**Comment by hwdef** [comment]
> Can we delete all jobs fristly, and then delete the queue; we can handle those actions in `QueueController`, similar to namespace.

It's really simpler, but I am worried that this will delete the job by mistake.
What if when deleting a queue, check if there are still jobs in the queue, and refuse to delete the queue if there are jobs?
I'm not sure which one to use, the one you said looks good and is more in line with the logic of kubernetes.

**Comment by Yikun** [comment]
From api view, I think it's reasonable, 

then we can use yaml to control queue deletion, and I'm not sure the final UX for this.

I hope just use kubectl apply yaml to set queue spec rather than kubectl volcano plugin or something. 

Because we still need to allow users use API interfaces(golang API/java API) to set spec. The better way is use crd capability directly.

**Comment by Yikun** [comment]
And we might want to think about the rleationship of original state and spec.state.

**Comment by jyn244636695** [comment]
Is this question have been solved?

**Comment by hwdef** [comment]
> Is this question have been solved?

no, this isuse is closed.
