### ISSUE TITLE
[feature request] set the init container of volcano job as privileged mode

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#2123]
https://github.com/volcano-sh/volcano/blob/db2936fd44f304862a6f1888204fb41ed44ede6d/pkg/webhooks/admission/jobs/validate/admit_job.go#L278-L284

obviously, volcano forgets to cover the init container case ... and once the init container set the `privileged` field, it turns out

```
Error from server: error when creating "vj-test.yaml": admission webhook "validatejob.volcano.sh" denied the request: spec.task[0].template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy.
```

**Comment by wpeng102** [comment]
> /kind bug

I am not sure if the original logic to `Skip verify container SecurityContex.Privileged` is appropriate. The root cause is kube-apiserver configured `--allow-privileged=true` and kube-apiserver will use this config to init  `capabilities`. But the volcano does not know the kube-apiserver configuration.

https://github.com/volcano-sh/volcano/blob/db2936fd44f304862a6f1888204fb41ed44ede6d/vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go#L6150-L6154

 If volcano use the same logic to valid pod, it maybe mismache by kube-apiserver.
https://github.com/volcano-sh/volcano/blob/db2936fd44f304862a6f1888204fb41ed44ede6d/pkg/webhooks/admission/jobs/validate/admit_job.go#L295

So, maybe we need introduce `allow-privileged` flag for volcano webhook, which need guide users to config same value as kube-apiserver.

**Comment by k82cn** [comment]
IMO, we just need to skip this check in Volcano, and deligate this to kube-apiserver :)
