### ISSUE TITLE
what's the correct usage of `tiers` in volcano-scheduler.conf

### ISSUE THREAD

**Issue by zhiyxu** [volcano-sh/volcano#2147]
**What happened**:
Recently we met some strange things, some task of volcano job evicted by scheduler, **but we didn't set any `priorityClassName` field for any tasks or jobs**, then we found the following logs:

```
I0404 06:59:37.240558       1 preempt.go:208] Considering Task ... on Node <ml-gpu-ser144.nmg01>.
I0404 06:59:37.240581       1 priority.go:94] Can not preempt task ... because preemptee job has greater or equal job priority (0) than preemptor (0)
I0404 06:59:37.240589       1 priority.go:111] Victims from Priority plugins are []
I0404 06:59:37.240614       1 drf.go:323] Victims from DRF plugins are [Task (c4bc5b12-508d-4e61-a052-db4dc540f358:...): job ..., status Running, pri 0resreq cpu 8000.00, memory 96636764160.00, nvidia.com/gpu 4000.00, preemptable false, revocableZone , TopologyPolicy ]
I0404 06:59:37.240651       1 preempt.go:242] Try to preempt Task <...> for Tasks <...>
I0404 06:59:37.240698       1 drf.go:509] DRF EvictFunc: task <...>, resreq <cpu 8000.00, memory 96636764160.00, nvidia.com/gpu 4000.00>,  share <0.007821666014861166>, namespace share <0.05475166210402816>
...
I0404 06:59:37.241136       1 cache.go:150] Evicting pod ..., because of preempt
``` 

It seems that task is preempted by drf plugin, instead of priority. The scheduler config is as follows:
```
  volcano-scheduler.conf: |
    actions: "enqueue, reclaim, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```
And [the preemption plugin code](https://github.com/volcano-sh/volcano/blob/ac3b31334b8b754ee2fd17af455cbeb92fde852e/pkg/scheduler/framework/session_plugins.go#L202) shows that, **it takes the intersection of the results within a `Tier` and the union of the results between different `Tiers`**. 

This problem is very hidden to us. Volcano's parameter configuration seems to be extensive and profound, such as drf would preempt, such as Tier in config. In order to avoid such problems, where can we find documentation for the correct use of each parameter?

**What you expected to happen**:
precise document.

**How to reproduce it (as minimally and precisely as possible)**:
Use above scheduler config, some task could be preempted in scheudler.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.4.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kenoung** [comment]
I actually think that this is a bug. I filed a related issue [here](https://github.com/volcano-sh/volcano/issues/1791), and made a PR [here](https://github.com/volcano-sh/volcano/pull/1790).

>  it takes the intersection of the results within a Tier and the union of the results between different Tiers.

We don't take the union between tiers. If the first tier already returns some victims, then it won't proceed to the next tier. 
https://github.com/volcano-sh/volcano/blob/ac3b31334b8b754ee2fd17af455cbeb92fde852e/pkg/scheduler/framework/session_plugins.go#L481-L484

The behavior becomes interesting when tier 1 returns no victims.
If the *first plugin* in tier 1 returns no victims, then we proceed to tier 2. In this case, we would return the union between tier 1 and tier 2.
However, if the *first plugin* in tier 1 returns some victims, but the **intersection of the results within tier 1** is nil, we proceed to tier 2 but return nil regardless of the decisions in tier 2 since we don't reset our `init` variable to `false` for each tier. i.e. for every plugin in tier 2, we'll take the intersection between a nil slice and the candidates found.

https://github.com/volcano-sh/volcano/blob/ac3b31334b8b754ee2fd17af455cbeb92fde852e/pkg/scheduler/framework/session_plugins.go#L463-L466

I'm still unclear about how tiers are intended to work, so I'm not sure how to properly fix the issue, but I'm fairly confident that some of this is unintentional and there's a bug here.
