### ISSUE TITLE
Add Volcano into Helm Charts 

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#216]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

It's better to also submit volcano helm chart to helm/charts by following its guidance: https://github.com/helm/charts/blob/master/CONTRIBUTING.md . It should be incubator.

**Comment by asifdxtreme** [comment]
cc @thandayuthapani

**Comment by thandayuthapani** [comment]
@k82cn Have raised PR regarding this issue, Please have a Look. https://github.com/helm/charts/pull/14692

**Comment by thandayuthapani** [comment]
@k82cn We need to have seperate repo for charts under volcano-sh repo and enable github pages for that repo, so that we can host our package ourselves, since we are not adding in helm/charts, we need to host it ourselves and put the hosted info in helm/hub so that user can see and download. 
So @k82cn can you create a repo like volcano-sh/charts and enable github pages to its master branch?

**Comment by thandayuthapani** [comment]
Creating new repo might not be necessary, we can use github rawcontent url to get that index.yaml, and we can maintain chart package in github itself.  we don't need to maintain new repo.  Only if any change in charts should be reflected back to chart package(.tgz file) file.

**Comment by thandayuthapani** [comment]
@k82cn Volcano has been added in hub.helm.sh site, so I think we can close this issue.
![Screenshot from 2019-06-20 09-20-03](https://user-images.githubusercontent.com/34565833/59817207-b2499b80-933c-11e9-9a71-901a442e8c7e.png)

**Comment by k82cn** [comment]
that's ok to me :)
