### ISSUE TITLE
PodGroupCompleted is not used

### ISSUE THREAD

**Issue by acmore** [volcano-sh/volcano#2642]
There is a new status `PodGroupCompleted` but in the scheduler code, this podgroup status is not in used.

We would like to add a new kind of job and make volcano support it. May I ask what's the state transition rule for the podgroup? If the job is completed, do we need to delete the podgroup?

**Comment by acmore** [comment]
> To my understanding, `PodGroupCompleted` is added to accurately calculate tasks into the queue, mainly for other non-vcjob workloads, such as `paddlejob`, for details, please refer to: [#2056](https://github.com/volcano-sh/volcano/issues/2056)
> 
> `podgroup` can control the life cycle according to its `ownerReferences`, please refer to: [Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod.md](https://github.com/volcano-sh/volcano/blob/master/docs/design/Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod.md)

Thanks for the reply! Seems like the `PodGroupCompleted` status will be changed to `inqueue` immediately if we update a podgroup to `PodGroupCompleted`. Is it expected?

**Comment by wangyang0616** [comment]
Is there an action to configure enqueue in the configmap of the volcano in your environment? If it is configured, this problem should not occur, because enqueue will only update the podgroup status for tasks in the pending state; if it is not configured, it may indeed be allocated Set to inqueue state.

as follows：
https://github.com/volcano-sh/volcano/blob/e145aff85f7f479d1fde178a2053d50f762c878b/pkg/scheduler/actions/enqueue/enqueue.go#L70-L75

https://github.com/volcano-sh/volcano/blob/e145aff85f7f479d1fde178a2053d50f762c878b/pkg/scheduler/actions/allocate/allocate.go#L64-L66
