### ISSUE TITLE
How can I adapt volcano to another metrics platform, like influxdb or ELK stack?

### ISSUE THREAD

**Issue by Shoothzj** [volcano-sh/volcano#2674]
How can I adapt volcano to another metrics platform, like influxdb? Thanks for your reply.

**Comment by wangyang0616** [comment]
This issue was just discussed at the weekly community meeting. Currently, the rescheduling function supports obtaining monitoring data from prometheus. Can it support obtaining monitoring data from other platforms, such as influxdb.

@Shoothzj Can you enrich the specific information in the issue, such as application scenarios, desired goals, etc.  thanks!

**Comment by Shoothzj** [comment]
closed by #2679
