### ISSUE TITLE
Optimizing rescheduling plugin in Volcano community to use eviction and leverage PDB constraints

### ISSUE THREAD

**Issue by Shoothzj** [volcano-sh/volcano#2754]
The rescheduling plugin in the Volcano community currently uses deletion as a method of rescheduling, which can lead to data loss and longer application downtime. To optimize rescheduling operations and improve resource utilization, we suggest using eviction instead of deletion and leveraging Pod Disruption Budget (PDB) constraints.

PDBs are a Kubernetes feature that can be used to ensure high availability of applications during rescheduling operations. PDBs allow you to set constraints on how many pods of a given application can be down simultaneously. By leveraging PDB constraints in conjunction with eviction, we can ensure that rescheduling operations maintain the desired level of availability for our applications.

Therefore, we suggest optimizing the rescheduling plugin in the Volcano community to use eviction and leverage PDB constraints. This will ensure smoother rescheduling operations, reduce data loss and application downtime, and improve resource utilization in the cluster. We welcome feedback and suggestions from the community on this optimization proposal.

**Comment by heiliuchao** [comment]
Plan A: Change the delete interface to the evict interface. All actions call the evict interface. After the PDB is verified, the pod is deleted. But，this will break the forward compatibility of the version. Some actions, such as Preempt, do not require the evict interface.

**Comment by heiliuchao** [comment]
Our requirement is that some microservices need to ensure high availability and do not want to be evicted to prevent data loss. We hope to use the native eviction capability, that is, API-initiated eviction, in pod evicting scenarios and use the PDB capability to ensure the pod budget. 
Currently, Volcano has three actions, such as reclaim, preempt, and shufffle, which call the Evict function. Other actions, such as allocate, backfill, and enqueue, do not use the Evict function. The Evict function invokes the delete interface of the pod to process the victim pods. 
From the perspective of availability, the native eviction interface of the pod is better than the delete interface. This is because it can ensure the pod budget of related microservices when the administrator configures the PDB. If the PDB is not configured, it automatically degenerates to the delete interface. In fact, it's essentially compatible with previous versions.

**Comment by wangyang0616** [comment]
I understand that if Volcano needs to support the PDB strategy when expelling pods, you may need to consider more things. You cannot just change the delete interface used by the underlying Volcano scheduling to evict.

If you modify it directly, it may cause Volcano to expel a batch of pods in the current cycle. However, this batch of pods is protected by the PDB policy, and the eviction fails. If the environment status does not change, the same batch may be evicted in each cycle. pod, and it fails every time, in a continuous loop.

When my task Volcano triggers pod eviction due to preemption and rescheduling, I need to add PDB policy judgment to filter pods that do not comply with the PDB policy, and then I can perform eviction-related actions.

In addition, the current k8s community is also discussing the cooperation between priority preemption and PDB strategy, refer to: [#91492](https://github.com/kubernetes/kubernetes/issues/91492)

**Comment by wangyang0616** [comment]
The current feature has participated in [OSPP 2023](https://summer-ospp.ac.cn/org/prodetail/233ba0295?list=org&navpage=org). Students who are interested in this feature can pay attention to and register for the project through OSPP.

The community will communicate with students through OSPP, and after the two-way selection (expected at the end of June), it will be announced and assigned.

**Comment by wangyang0616** [comment]
Thank you very much for your attention to the current features, temporarily cancel the assignment.
/unassign @qihuang0

**Comment by xiao-jay** [comment]
@wangyang0616 @Shoothzj I'm interested in this project, but I can't get started, Can you give me a guide？
