### ISSUE TITLE
Is it necessary to panic the scheduler when resources are misconfigured?

### ISSUE THREAD

**Issue by lut777** [volcano-sh/volcano#3929]
### Please describe your problem in detail

In plugin Capacity, the '''realCapability' would be obtained with following code:
```go
119			realCapability := cp.totalResource.Clone().Sub(cp.totalGuarantee).Add(attr.guarantee)
```

But if the resources of queues were misconfigured, this code would lead to a scheduler panic.
Well this happened to us, with the panic triggered from this assert 
```go
// Sub subtracts two Resource objects with assertion.
func (r *Resource) Sub(rr *Resource) *Resource {
	assert.Assertf(rr.LessEqual(r, Zero), "resource is not sufficient to do operation: <%v> sub <%v>", r, rr)
	return r.sub(rr)
}
```
So I'm wondering, is this panic deliberately designed?

**Comment by JesseStutler** [comment]
Yes, that's how it's designed. As a cluster administrator, we need to set the guarantee to a value smaller than the realCapability. When the cluster resources are scaled down, we must also ensure that the realCapability is greater than the guarantee. Otherwise, the plugin calculation will not meet expectations. The guarantee should be set to a reasonable value in advance.

**Comment by lut777** [comment]
sounds reasonable, THX！
