### ISSUE TITLE
Support zone aware scheduling

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#447]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

The nodes in the cluster maybe from different zones; there maybe several benefits if all tasks of the job were scheduled to the same zone, e.g. low latency. So it's better for Volcano to support zone aware scheduling :)

**Comment by Jeffwan** [comment]
Thanks for @k82cn creating this issue.  Add my requirements here.

Basically, in order to get higher availability and mitigate the risk of not having enough capacity in single AZ, users create EKS worker node groups across multiple availability zones (AZs). 

For **spark** applications, *Shuffling* is very common and it’s a process of redistributing data across partitions that may or may not cause moving data across JVM processes or even over the wire (between executors in different zones). It has two downsides, 

The first one is network overhead between different Availability Zones within a region. 
The second thing is extra cost for cross-zone data transfer. 

In order to mitigate this issue, it’s better for scheduler to be availability-zone aware, scheduler can fit as many executors for a single job in one AZ as possible.  

This feature is mainly for **spark**. for **distributed training** case like MPI,  the performance is determined by slowest node in the ring, network latency is key factor to the speed of every iteration. At moment, we use single AZ cluster.

**Comment by k82cn** [comment]
> Kubernetes reserves this label `failure-domain.beta.kubernetes.io/zone` and we do use it for zone identity. Not sure if all vendors has it.

That's great! We'll make it configurable :)
