### ISSUE TITLE
Release v0.3

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#635]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

We'd like to have v0.3 release this week, this issue is used to trace all related items for the release.

- [x] cut branch (release-0.3)
- [x] change log
- [x] publish docker images
- [x] publish packages

**Comment by hzxuzhonghu** [comment]
I can pick up  `publish docker images`, and i donot have permission for the other two.

**Comment by Eo300** [comment]
Within the page of [Release v0.3](https://github.com/volcano-sh/volcano/releases/tag/v0.3), a tarball like those present in versions [v0.1](https://github.com/volcano-sh/volcano/releases/tag/v0.1) and [v0.2](https://github.com/volcano-sh/volcano/releases/tag/v0.2) seems to be missing.  Is this intentional?

I ask because downloading the source files present and using the installation helm chart downloads images via the "latest" tag, which I assume would retrieve a possible development image rather than a stable one.

**Comment by k82cn** [comment]
@Eo300 , thanks very much for your input! That's right, we should update version to 0.3 in installer. I'll open an PR for it.

**Comment by k82cn** [comment]
Meanwhile, please modify `installer/helm/chart/volcano/values.yaml` to set `image_tag_version` to `v0.3` manually.
