### ISSUE TITLE
Running Spark jobs with volcano scheduler using spark-submit 

### ISSUE THREAD

**Issue by gouthamreddykotapalle** [volcano-sh/volcano#910]
I am currently able to run Spark jobs using the spark-on-k8s-operator but I am not sure how to run a Spark job using spark-submit. The example in the volcano repository also uses spark operator.

Could someone please elaborate on how to run Spark jobs with volcano scheduler using spark-submit (with gang-scheduling using enqueue + minResources)?

**Comment by QizhouYang** [comment]
Prerequisites, run spark-on-k8s-operator，Because it depends on webhooks
First step:
Create `PodGroup`, reference spark-on-k8s-operator -> volcano_scheduler.go -> syncPodGroup function

Second step:
Add annotation ,  reference spark-on-k8s-operator -> volcano_scheduler.go -> syncPodGroupInClusterMode,
and, [spark official website]( http://spark.apache.org/docs/latest/running-on-kubernetes.html) (`spark-sumbit --config spark.kubernetes.{driver,executor}.annotation.* ...`)

if you encounter problems,we can discuss.

**Comment by Gouthamkreddy1234** [comment]
Sure! This makes sense. I will try this :)

Also, I am facing one problem with spark-on-k8s operator which I have raised here - 
[https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/968
](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/968)

Could you please help me with this and let me know what the problem could be?

**Comment by Gouthamkreddy1234** [comment]
@QizhouYang I tried the above approach but these are the events I see -

1. The driver pod is being scheduled by the default-scheduler and not volcano scheduler
2. PodGroup that I initially create does not get updated with the driver+executor resources.

Could you please clarify how this job would be scheduled by volcano-scheduler? Also, how do the webhooks actually work from spark-on-k8s-operator perspective?

Also, what would be the control flow when I submit the spark job through spark-submit and how does the interaction with volcano scheduler and spark-operator work?

**Comment by Gouthamkreddy1234** [comment]
@QizhouYang Could you please help me debug this issue?

Thanks!

**Comment by iddelacruz** [comment]
@Gouthamkreddy1234 Right now I'm having the same issue. My spark is scheduled by default-scheduler. How do you fix this problem? Tx

**Comment by k82cn** [comment]
when submit the Pod, the `schedulerName` should be set to volcano's name, e.g. volcano
