### ISSUE TITLE
v1.1 feature design: design and implementation of resource reservation for big job

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#947]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
> /kind feature

**What happened**:
volcano cannot reserve resource for big job in current version
**What you expected to happen**:
required work:
  - provide solution design
  - design implementation
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
@Thor-wl

**Comment by Thor-wl** [comment]
@Gouthamkreddy1234 Can you make an introduction of the usage scenarios？

**Comment by Gouthamkreddy1234** [comment]
@Thor-wl Sure! Let me draft a list of usage scenarios. I will keep you posted on this thread.

**Comment by Gouthamkreddy1234** [comment]
These will be the primary usage scenarios - 

**Case 1:**
When we have insufficient resources in the cluster, the jobs with large resource requirements (with equal priority as smaller jobs) will be at risk of starvation. The job that can not be scheduled for a long time due to insufficient resources is called a starving job. If the Volcano scheduler continually launches small applications while small amounts of resources become available, larger applications may never get scheduled at all.

**Case 2:**
In a shared cluster, we may have jobs of different priorities, e.g. high priority job, low priority job. The user always expects a high priority job to be scheduled first. But in some cases when there are insufficient resources that could be allocated to a high priority job, Volcano scheduler will ignore this job and try to schedule a lower priority job. In the worst case, the high priority job will keep waiting until the low priority job releases sufficient resources (i.e. the high priority job will be starvation till then). This may not be acceptable to the user.

As per the current design, the problem would be aggravated due to the backfill action when trying to achieve *gang-scheduling* of jobs as we try to backfill smaller/lower priority jobs behind in the queue to make better use of idle resources. But this could potentially again result in the bigger/high priority job getting starved. Hence, we will handle this use case as well using resource reservations. In case we implement a reserve action to handle our reservations, this reserve action will be run before the backfill action and can be enabled by default.

</br>

**Use case in current version without reservations:**
![image](https://user-images.githubusercontent.com/9594685/90579195-e01db080-e18a-11ea-90a1-764ca713089c.png)

**Use case with resource reservations:**
![image](https://user-images.githubusercontent.com/9594685/90579250-0fccb880-e18b-11ea-971d-8125cfb54168.png)

Hence, when node resources are occupied by lower priority pods with relatively small resource requirements for a long time, the remaining resources of the node can not satisfy the scheduling condition of this task. Hence, the task that demands large resources can not be scheduled due to insufficient resources. In extreme cases, tasks with large resource requirements can only be scheduled when all the small resource application pods are completed. This situation needs to be avoided as much as possible. When a task cannot be scheduled for a long time, a special scheduling mechanism needs to be provided for it to ensure that the task can be scheduled as soon as possible. This is when our reservations come into the picture.

**Comment by Thor-wl** [comment]
@Gouthamkreddy1234 Thanks a lot! It's very import for me to make the feature design

**Comment by Thor-wl** [comment]
https://github.com/volcano-sh/volcano/pull/1011  Feature design v1.0 is uploaded. Disscuss is going.

**Comment by Gouthamkreddy1234** [comment]
@Thor-wl Could you please update the status of this issue and link any active/closed PR?

**Comment by Thor-wl** [comment]
> @Thor-wl Could you please update the status of this issue and link any active/closed PR?

OK, related pr: https://github.com/volcano-sh/volcano/pull/1044. This implementation is just  a first draft which may not be so perfect. Any feedback is welcomed.
