### ISSUE TITLE
meaning of queue weight 

### ISSUE THREAD

**Issue by weiranzhixin** [volcano-sh/volcano#975]
what is the meaning of weight of queue?
as I can see the queue named 'default'  with weight 1, does it mean the default queue share 10% cluster resource?
then if it is right, which kind of resource will be shared: cpu, memory, or extended resource like GPU?
what is the action when client request resource more than queue weight?

**Comment by Thor-wl** [comment]
@weiranzhixin 
1. weight of queue means a relative share of cluster resource of the queue, it represents your request for queue, not a percentage. For example, considering a cluster with 4 cpu, volcano will create a queue named "default" by default and weight is 1. If no new queue created, default queue takes 4 cpu for use. Suppose a new queue named "q1" comes and its weight is 1. Then "default" and "q1" both takes 2 cpu for use. It is to be emphasized that before job comes to "q1", namely there is no job in "q1", "default" can still take 4 cpu for use until new jobs comes to "q1". It's more flexible and efficient to make use for cluster resource
2. "default" queue takes 100% cluster resource for use before new queues are generated and new jobs come to the queue.
3. All resource will be shared
4. When client requests resource more than queue weight and there is enough resource for your request(no other queues or other queue' resource share has not been fully used), client's request will be satisfied. Otherwise, client' job will be pending. Actually, queue weight is a soft limit for resource.

Material about Volcano is not so complete now and we have already taken the requirement into v1.1
