### ISSUE TITLE
Benchmark on volcano scheduler

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#999]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

As more and more users are asking is there a benchmark for volcano. It is fairly reasonable to have a scalability performance test on volcano.

As talked on volcano community meeting, @carmark from Tencent has done some similar tests. 
IMO, the below benchmark should be provided: we can use [kubemark](https://stupefied-goodall-e282f7.netlify.app/contributors/devel/kubemark-guide/) to simulate k8s node

1. Schedule a large number of pods(like 100k) onto a cluster with thousands of nodes(1k-5k).
Calculate the throughout of scheduler.

2. Simulate creating pods with a fixed frequency and calculate the average scheduling latency. 

3. Advanced test should include devices(like GPU) and repeat the above tests. 

cc @carmark Need your input here

**Comment by alcorj-mizar** [comment]
In general, the performance of an online business system is evaluated in terms of the QPS that the system is capable of hosting and the TP99 latency of the response.

The scheduling system differs from the online business system in that the performance of the scheduling system cannot be evaluated with the response latency of RPC . The reason is that these RPC calls are asynchronous from the scheduling process of the scheduling system, so the RPC response is almost unaffected by poor scheduling performance. Similarly, scheduling performance is almost unaffected by the poor RPC response.

Therefore, we need a pressure simulator for volcano scheduler that can simulate the scheduling process of volcano without a large amount of physical machine resources, and can set the random job running duration in acceptable range.

**Comment by Thor-wl** [comment]
@alcorj-mizar Is there any process or idea for v1.3 and later versions?

**Comment by fjding** [comment]
Where to find performance test reports
